### PR TITLE
Add health check

### PR DESCRIPTION
**Pull request by goose-ws**
Because healthy containers are happy containers!

### CODE REVIEW

**Comment by mp-se** [comment]
Great idea, will try it out this weekend and perhaps this can be extended to do a more checks of the container... from an exensibility perspective i suggest we move the checks to a separate script in the container that can be called from dockercompose and then new checks can be added later om. From what i can see you can only have one healthcheck script per container. 

Do you know if this is specific to docker compose or can it be done from standard docker?

**Comment by mp-se** [comment]
I've moved the healthcheck to the docker image so it can be used without docker compose as well. I have pushed a version to the dev branch but want to do some more testing before it's pushed to master. Feel free to build and test yourself. 

It's now checking circusd, nginx, django and redis. Circusd should keep track of all the individual parts of fermentrack and if that fails it will exit/stop the container.

**Comment by goose-ws** [comment]
Just beware that your `grep` is still going to return an exit code of zero, as it will find itself (the `grep circusd` process). You may want to adjust your commands to be more like:

```
if ps -ax | grep -v grep | grep -q circusd > /dev/null
```

I'm not easily able to make a pull request right now, or I'd offer a patch myself.

**Comment by goose-ws** [comment]
Alternatively, pgrep provides a way to search for a process without including that grep process itself. Downside is, it doesn't offer a `-q` flag.

```
if pgrep circusd > /dev/null 2>&1
```

**Comment by mp-se** [comment]
Missed that one. I might as well remove that first part because if circusd is not running the container would have exited anyway since that is the last  command  in the startup script. So have not been able to test that part. 

I get docker to report the container as unhealty but it's not restarted. From what I can tell it should do so if the restart = always is set.

**Comment by goose-ws** [comment]
I'm not sure about native restart behavior, as I use the `autoheal` container/project to restart my unhealthy ones

**Comment by mp-se** [comment]
From what I can find on the internet there is no action built in for handling unhealthy containers so you need some kind of add-on... I will fix the bug and test the build on all targets before pushing it to master.

**Comment by mp-se** [comment]
The image with healthcheck is now available on docker-hub (tag:latest). 

I had issues with buildx that somehow caused the build on arm to fail. If it works as expected please let me know and I will promote this build to v0.7

**Pull request merged**
